# -*- python -*-
Import("env")

pkg = env["eups_product"]
env.CheckSwig("python", ilang="c++", includedProducts="utils daf_base pex_exceptions")
env.LoadableModuleIncomplete("_sdqaLib", ["sdqaLib.i"], LIBS=env.getlibs(pkg))
