# -*- python -*-
Import("env")
import glob

env.Program(["testSdqaMetric.cc"], LIBS=env.getlibs(env["eups_product"]))
env.Program(["testSdqaThreshold.cc"], LIBS=env.getlibs(env["eups_product"]))
env.Program(["testSdqaRating.cc"], LIBS=env.getlibs(env["eups_product"]))
env.Program(["testSdqaRatingSet.cc"], LIBS=env.getlibs(env["eups_product"]))
env.Program(["testSdqaImageStatus.cc"], LIBS=env.getlibs(env["eups_product"]))

#
# Tests
#
import lsst.tests

tests = lsst.tests.Control(env, verbose = True)
tests.run("*.cc")

# This one seems a bit harder to make generic.
for target in tests.run("*.py"):
     env.Depends(target,
        "../python/lsst/sdqa/_sdqaLib%s" % (env['LDMODULESUFFIX']))


